---
- name: Set up DevOps environment
  hosts: localhost
  become: yes

  vars:
    username: "cloudikeme"
    user_uid: "{{ ansible_user_uid }}"
    user_gid: "{{ ansible_user_gid }}"
    git_email: "cloudikeme@gmail.com"
    git_name: "cloudikeme"
    miniconda_version: "latest"
    go_version: "1.22.5"
    kind_version: "v0.23.0"
    kubectl_version: "v1.30.0"
    

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - sudo
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
          - zsh
          - git
          - python3
          - python3-pip
          - ffmpeg
          - libsm6
          - libxext6
          - ghostscript
          - python3-tk
          - xvfb
          - libx11-6
          - libxext6
          - libxtst6
          - libxrender1
          - libxft2
          - libxpm4
          - libxmu6
          - libxaw7
          - lsb-release
          - wget
        state: present

    - name: Add user to sudo group
      user:
        name: "cloudikeme"
        groups: sudo
        append: yes

    - name: Allow sudo without password for user
      lineinfile:
        path: /etc/sudoers.d/{{ username }}
        line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        create: yes
        mode: 0440

    - name: Configure Git
      become_user: "{{ username }}"
      git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      loop:
        - { name: 'user.email', value: '{{ git_email }}' }
        - { name: 'user.name', value: '{{ git_name }}' }
        - { name: 'core.autocrlf', value: 'false' }

    - name: Install GitHub CLI
      block:
        - name: Download GitHub CLI GPG key
          get_url:
            url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
            dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
            mode: '0644'

        - name: Add GitHub CLI repository
          apt_repository:
            repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
            state: present
            filename: github-cli

        - name: Install GitHub CLI
          apt:
            name: gh
            state: latest
            update_cache: yes
            

    - name: Configure bash
      become_user: "{{ username }}"
      blockinfile:
        path: "/home/{{ username }}/.bashrc"
        block: |
          source <(kubectl completion bash)
          alias k=kubectl
          complete -F __start_kubectl k
          source <(kind completion bash)

    - name: Set bash as default shell
      user:
        name: "{{ username }}"
        shell: /usr/bin/bash

    - name: Generate en_US.UTF-8 locale
      locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Add user to docker group
      user:
        name: "{{ username }}"
        groups: docker
        append: yes

    - name: Install KinD
      block:
        - name: Download KinD
          get_url:
            url: "https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64"
            dest: "/usr/local/bin/kind"
            mode: '0755'

        - name: Add KinD completion to .bashrc
          lineinfile:
            path: "/home/{{ username }}/.bashrc"
            line: 'source <(kind completion bash)'

    - name: Install kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Install kubectx and kubens
      get_url:
        url: "https://github.com/ahmetb/kubectx/releases/download/v0.9.5/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: '0755'
      loop:
        - kubectx
        - kubens

    - name: Install Miniconda
      become_user: "{{ username }}"
      block:
        - name: Download Miniconda installer
          get_url:
            url: "https://repo.anaconda.com/miniconda/Miniconda3-{{ miniconda_version }}-Linux-x86_64.sh"
            dest: "/tmp/miniconda.sh"
            mode: '0755'
        - name: Install Miniconda
          shell: "/tmp/miniconda.sh -b -p $HOME/miniconda"
          args:
            creates: "$HOME/miniconda"
        - name: Add Miniconda to PATH
          lineinfile:
            path: "/home/{{ username }}/.bashrc"
            line: 'export PATH="$HOME/miniconda/bin:$PATH"'
        - name: Initialize conda for bash
          shell: "$HOME/miniconda/bin/conda init"

    - name: Install Go
      block:
        - name: Download Go
          get_url:
            url: "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz"
            dest: "/tmp/go.tar.gz"
        - name: Extract Go
          unarchive:
            src: "/tmp/go.tar.gz"
            dest: "/usr/local"
            remote_src: yes
        - name: Add Go to PATH
          lineinfile:
            path: "/home/{{ username }}/.bashrc"
            line: 'export PATH=$PATH:/usr/local/go/bin'
        - name: Create Go workspace directories
          file:
            path: "/home/{{ username }}/go/{{ item }}"
            state: directory
            owner: "{{ username }}"
            group: "{{ username }}"
          loop:
            - src
            - pkg
            - bin
        - name: Set GOPATH
          lineinfile:
            path: "/home/{{ username }}/.bashrc"
            line: 'export GOPATH=$HOME/go'
    
    - name: Add kubectl autocomplete and alias to .bashrc
      lineinfile:
        path: "/home/{{ username }}/.bashrc"
        line: "{{ item }}"
      loop:
        - "source <(kubectl completion bash)"
        - "alias k=kubectl"
        - "complete -F __start_kubectl k"

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted